### ISSUE TITLE
[BUG] Cockpit reporting Firfox as too old

### ISSUE THREAD

**Issue by iproud** [linuxserver/docker-firefox#25]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When opening Cockpit in docker-firefox I now get the following error in Cockpit.

This web browser is too old to run the Web Console (missing selector(:is():where()))

The firefox version in KasmVNC is: 109.0.1

The issues only started after the container was updated from what I believe was a guacamole VNC to the KasmVNC

### Expected Behavior

Navigating to localhost:9090 through docker-firefox should allow the user to log into Cockpit on Ubuntu and manager the server.

### Steps To Reproduce

1. Setup docker on Ubuntu 22.0.1
2. Setup Portainer on docker
3. Create the stack using docker compose syntax and deploy
4. Navigate to localhost:3000
5. Visit localhost:9090 to navigate to Cokpit
6. Error message present on landing page preventing login

### Environment

```markdown
- OS:Ubuntu 22.0.1
- How docker service was installed:Install via Portainer as a stack.
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "2.1"
services:
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      #- TZ=Australia/Victoria
    volumes:
      - /home/user/docker/firefox:/config
      - /home/user/:/files
      - proudserver2:/proudserver2
    ports:
      - 3010:3000
    shm_size: "4gb"
    restart: unless-stopped
    labels:
       com.centurylinklabs.watchtower.enable: "true"

  auto_update:
    image: containrrr/watchtower:latest-dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # Update check interval in seconds.
    command: --schedule "0 0 * ? * *" --label-enable --cleanup
    restart: unless-stopped
volumes:
  user:
    external: true
```

### Container logs

```bash
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
[custom-init] No custom files found, skipping...
[ls.io-init] done.
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
Xvnc KasmVNC 1.1.0 - built Apr 10 2023 21:26:03
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12014000, The X.Org Foundation
Obt-Message: Xinerama extension is not present on the server
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: Unrecognized feature ACCELERATED_CANVAS2D (t=5.86638) [GFX1-]: Unrecognized feature ACCELERATED_CANVAS2D
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
[custom-init] No custom files found, skipping...
[ls.io-init] done.
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
Xvnc KasmVNC 1.1.0 - built Apr 10 2023 21:26:03
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12014000, The X.Org Foundation
Obt-Message: Xinerama extension is not present on the server
Error: Connection refused
    at PulseAudioContext.<anonymous> (/kclient/node_modules/pulseaudio2/lib/pulse.js:120:36)
    at /kclient/node_modules/pulseaudio2/lib/pulse.js:133:21
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
Kclient was unable to init audio, it is possible your host lacks support!!!!
Error: Access denied
    at /kclient/node_modules/pulseaudio2/lib/pulse.js:133:21
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
Kclient was unable to init audio, it is possible your host lacks support!!!!
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: Unrecognized feature ACCELERATED_CANVAS2D (t=0.949904) [GFX1-]: Unrecognized feature ACCELERATED_CANVAS2D
 2023-04-13 01:25:25,628 [INFO] websocket 0: got client connection from 127.0.0.1
 2023-04-13 01:25:25,637 [PRIO] Connections: accepted: @104.28.217.24_1681349125.628644::websocket
 2023-04-13 01:25:27,394 [PRIO] Connections: closed: @104.28.217.24_1681349125.628644::websocket (Clean disconnection)
 2023-04-13 01:25:30,386 [INFO] websocket 1: got client connection from 127.0.0.1
 2023-04-13 01:25:30,418 [PRIO] Connections: accepted: @104.28.217.24_1681349130.386265::websocket
ATTENTION: default value of option mesa_glthread overridden by environment.
 2023-04-13 03:25:04,322 [PRIO] Connections: closed: @104.28.217.24_1681349130.386265::websocket (Clean disconnection)
 2023-04-13 05:18:00,296 [INFO] websocket 2: got client connection from 127.0.0.1
 2023-04-13 05:18:00,305 [PRIO] Connections: accepted: @104.28.217.24_1681363080.296411::websocket
ATTENTION: default value of option mesa_glthread overridden by environment.
 2023-04-13 05:33:22,835 [INFO] websocket 3: got client connection from 127.0.0.1
 2023-04-13 05:33:22,847 [PRIO] Connections: accepted: @172.19.0.1_1681364002.835820::websocket
 2023-04-13 05:33:41,613 [PRIO] Connections: closed: @104.28.217.24_1681363080.296411::websocket (Clean disconnection)
 2023-04-13 05:33:46,413 [INFO] websocket 4: got client connection from 127.0.0.1
 2023-04-13 05:33:46,422 [PRIO] Connections: accepted: @104.28.217.24_1681364026.413923::websocket
 2023-04-13 05:33:59,403 [PRIO] Connections: closed: @172.19.0.1_1681364002.835820::websocket (Clean disconnection)
 2023-04-13 05:34:11,199 [PRIO] Connections: closed: @104.28.217.24_1681364026.413923::websocket (Clean disconnection)
 2023-04-13 05:34:12,510 [INFO] websocket 5: got client connection from 127.0.0.1
 2023-04-13 05:34:12,519 [PRIO] Connections: accepted: @104.28.217.24_1681364052.510857::websocket
xterm: cannot load font "-misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso10646-1"
```

**Comment by thelamer** [comment]
Is this some kind of firefox plugin or something?  I honestly have no idea what you are talking about. Nothing is running on 9090 in this container.

**Comment by thelamer** [comment]
Closing due to lack of information.
